build:
    build_starting:
        image: python:2
        commands:
            - echo "Beginning new build"
    run_tests:
        image: python:2-alpine
        commands:
            - pip install -r requirements.txt
            - python testing.py

publish:
    docker:
        repo: perezg123/cicd_demoapp
        tag: latest
        username: perezg123
        password: E!d0rad0
        email: gabe@perezg.com
deploy:
    webhook:
        image: plugins/drone-webhook
        skip_verify: true
        method: POST
        auth:
            username: CICD1
            password: CICD1
        urls:
            - https://control.sandbox.imapex.io/marathon/v2/apps/class/perezg123/restart?force=true

notify:
    spark:
        image: hpreston/drone-spark
        auth_token: YzVjNWI3MTItMmNlYi00YmE3LTliNjQtNDU4NDE3ODYxZTViZDM5NzE4YzAtOTBk
        roomId: Y2lzY29zcGFyazovL3VzL1JPT00vODVmMzAzNTAtMTQwNC0xMWU3LTkxZWQtNjMzYWE4Y2FkZDNj
