build:
    build_starting:
        image: python:2
        commands:
            - echo "Beginning new build"
    run_tests:
        image: python:2-alpine
        commands:
            - pip install -r requirements.txt
            - python testing.py
publish:
    docker:
	repo: perezg123/cicd_demoapp
	tag: latest
	username: perezg123
	password: E!d0rad0
	email: gabe@perezg.com
